import type { Metadata } from "next";
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import CoursesSection from '../components/CoursesSection';
import CoursesCategory from '../components/CoursesCategory';
import Testimonials from '../components/Testimonials';  
import "./globals.css";
import { Varela_Round } from 'next/font/google'; // استيراد الخط

// تعريف الخط
const varelaRound = Varela_Round({
  weight: '400', // الخط في التصميم يبدو بوزن عادي
  subsets: ['latin'],
  variable: '--font-varela-round', // تعريف متغير CSS لاستخدامه في Tailwind
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${varelaRound.variable}`}>
          <>
          <body>
            
          
      <Navbar />
      {children}
      <Footer />
      </body>
    </>
    </html>
  );
}
